export const {
  FETCH_QUIZES_START,
  FETCH_QUIZES_SUCCESS,
  FETCH_QUIZES_ERROR,
  DELETE_QUIZ,
  FETCH_QUESTIONS_SUCCESS,
} = {
  FETCH_QUIZES_START: 'FETCH_QUIZES_START',
  FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
  FETCH_QUIZES_ERROR: 'FETCH_QUIZES_ERROR',
  DELETE_QUIZ: 'DELETE_QUIZ',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
}
